import Head from "next/head";
import Link from "next/link";
import Footer from "@/components/Footer";
import { useState } from "react";
import { addCampaign, getLastCampaignId } from "../services/Web3Service";

export default function Create() {

    const [campaign, setCampaign] = useState({});
    const [message, setMessage] = useState("");

    function onInputChange(evt) {
        setCampaign(prevState => ({ ...prevState, [evt.target.id]: evt.target.value }));
    }

    function btnSaveClick() {
        setMessage("Salvando...aguarde...");
        addCampaign(campaign)
            .then(tx => getLastCampaignId())
            .then(id => setMessage(`Campanha salva com ID: ${id}. Avise seus amigos e passe a eles esse número.`))
            .catch(err => {
                console.error(err);
                setMessage(err.message);
            })
    }

    return (
        <>
            <Head>
                <title>Doe Crypto | Criar Campanha</title>
                <meta charSet='utf-8' />
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <div className="container text-white" style={{ backgroundColor: '#000' }}>
                <div className="col-12 d-flex justify-content-center" style={{height: "85vh"}}>
                    <div className="col-9">
                        <div className="col-12 d-flex flex-column  align-items-center">
                            <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Doe Crypto</h1>
                            <p>Preencha os campos para incluir sua campanha na plataforma.</p>
                        </div>
                        <hr className="mb-4" />
                        <div className="col-12">
                            <div className="form-floating mb-3">
                                <input type="text" id="title" className="form-control" placeholder="Título" style={{ background: "#000", color: "#FFFFFF", borderRadius: "0px", border: "none", borderBottom: "1px solid gray" }} value={campaign.title} onChange={onInputChange} />
                            </div>
                            <div className="form-floating mb-3">
                                <textarea id="description" className="form-control" placeholder="Descrição" style={{ background: "#000", color: "#FFFFFF", borderRadius: "0px", border: "none", borderBottom: "1px solid gray" }} value={campaign.description} onChange={onInputChange} />
                            </div>
                            <div className="form-floating mb-3">
                                <input type="text" id="imageUrl" className="form-control" placeholder="URL da Imagem" style={{ background: "#000", color: "#FFFFFF", borderRadius: "0px", border: "none", borderBottom: "1px solid gray" }} value={campaign.imageUrl} onChange={onInputChange} />
                            </div>
                            <div className="form-floating mb-3">
                                <input type="text" id="videoUrl" className="form-control" placeholder="URL do Vídeo" style={{ background: "#000", color: "#FFFFFF", borderRadius: "0px", border: "none", borderBottom: "1px solid gray" }} value={campaign.videoUrl} onChange={onInputChange} />
                            </div>
                        </div>
                        <div className="col-12 mb-3">
                            <input type="button" className="btn btn-info col-12 p-3" value="Salvar Campanha" onClick={btnSaveClick} />
                        </div>
                        <div className="col-12 mb-3">
                            <Link href="/" className="btn btn-secondary col-12 p-3">Voltar</Link>
                        </div>
                    </div>
                </div>
                {
                    message
                        ? <div className="alert alert-success p-3 col-6" role="alert">{message}</div>
                        : <></>
                }
                <Footer />
            </div>
        </>
    )
}